name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'modernweb-dev/storybook-prebuilt'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Setup Git User
        run: |
          git config --global user.email "hello@modern-web.dev"
          git config --global user.name "Modern Web"

      - name: Release & Publish
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}